# Generated by Django 2.2.16 on 2023-02-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка на странице поста', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
